### ISSUE TITLE
Nicely done state machine

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [boczkas/OX#40]
With well thought out states and common interface for them. Though: is goToNextState even needed? Cause you are executing both methods in succession, each time, aren't you?

**Comment by boczkas** [comment]
It is giving me better clarity of code, but if you think that it would be better to handle states changes after performing all state actions then I can ofcourse change it.

**Comment by boczkas** [comment]
It gets more functionality now, so I will keep it
